pipeline {
  agent any
	{
		stage (list my env){
			steps{
			    echo(env.getEnvironment().collect({environmentVariable ->  "${environmentVariable.key} = ${environmentVariable.value}"}).join("\n"))
			}
		}
	}
}
